#
# This file is the manifest to determine which built items are copied to the
# hosted/Box file server locations. The versions that are specified within
# parenthesis below *must* match the versions from the version.properties file.
# They can also be overridden by passing values to the harvester script. ${see -versions}.
# It is best to keep the files and folders alphabetized because it makes it easier
# to compare the manifest to the filesystem. The exception to this is the ee/ce folder
# since most of the important artifacts are in the ee folder.
#

#EE Stuff
ee:
    client-tools:
        - pad-ee-${platform.version}-dist.zip
        - pdi-ee-client-${platform.version}-dist.zip
        - pdi-ee-client-${platform.version}-hadoop-addon-dist.zip
        - pentaho-analysis-ee-${platform.version}-dist.zip
        - pentaho-big-data-ee-package-${platform.version}-dist.zip
        - pme-ee-${platform.version}-dist.zip
        - pme-ee-${platform.version}-hadoop-addon-dist.zip
        - prd-ee-${platform.version}-dist.zip
        - prd-ee-${platform.version}-hadoop-addon-dist.zip
        - psw-ee-${mondrian.version}-dist.zip
    installers:
        - pentaho-business-analytics-${platform.version}-x64.app.tar.gz
        - pentaho-business-analytics-${platform.version}-x64.bin
        - pentaho-business-analytics-${platform.version}-x64.exe
        - pentaho-update-${platform.version}-Mac.zip
        - pentaho-update-${platform.version}-Windows.zip
        - pentaho-update-${platform.version}-Linux.zip
    other:
        - pentaho-operations-mart-${platform.version}-dist.zip
        - pentaho-sdk-${platform.version}-dist.zip
        - dock-maker-${platform.version}-public-dist.zip
    patches:
            windows:
                - AggregationDesigner-SP-${platform.version}.exe
                - PDIClient-SP-${platform.version}.exe
                - MetadataEditor-SP-${platform.version}.exe
                - PentahoServer-SP-${platform.version}.exe
                - ReportDesigner-SP-${platform.version}.exe
                - SchemaWorkbench-SP-${platform.version}.exe
                - BDPlugin-SP-${platform.version}.zip
                - SP-${platform.version}-Fixes.txt
                - README-SP-${platform.version}.txt
            mac:
                - AggregationDesigner-SP-${platform.version}.zip
                - PDIClient-SP-${platform.version}.zip
                - MetadataEditor-SP-${platform.version}.zip
                - ReportDesigner-SP-${platform.version}.zip
                - SchemaWorkbench-SP-${platform.version}.zip
                - BDPlugin-SP-${platform.version}.zip
                - SP-${platform.version}-Fixes.txt
                - README-SP-${platform.version}.txt
            linux:
                - AggregationDesigner-SP-${platform.version}.bin
                - PDIClient-SP-${platform.version}.bin
                - MetadataEditor-SP-${platform.version}.bin
                - PentahoServer-SP-${platform.version}.bin
                - ReportDesigner-SP-${platform.version}.bin
                - SchemaWorkbench-SP-${platform.version}.bin
                - BDPlugin-SP-${platform.version}.zip
                - SP-${platform.version}-Fixes.txt
                - README-SP-${platform.version}.txt
    plugins:
        - paz-plugin-ee-${platform.version}-dist.zip
        - pdd-plugin-ee-${platform.version}-dist.zip
        - pdi-ee-plugin-${platform.version}.zip
        - pentaho-monitoring-plugin-mib-assembly-${platform.version}-dist.zip
        - pir-plugin-ee-${platform.version}-dist.zip
        - hierarchical-datatype-plugin-${platform.version}-dist.zip
        - pentaho-streaming-kafka-plugin-zip-${platform.version}-dist.zip
        - elasticsearch-rest-plugin-${platform.version}-dist.zip
        - kafka-job-plugins-${platform.version}-dist.zip
    server:
        - pentaho-server-ee-${platform.version}-dist.zip
        - pentaho-server-manual-ee-${platform.version}-dist.zip
    shims:
        - pentaho-hadoop-shims-ee-cdh61-kar-${pentaho-hadoop-shims.version}-dist.zip
        - pentaho-hadoop-shims-ee-emr521-kar-${pentaho-hadoop-shims.version}-dist.zip
        - pentaho-hadoop-shims-ee-hdp30-kar-${pentaho-hadoop-shims.version}-dist.zip
        - pentaho-hadoop-shims-ee-dataproc1421-kar-${pentaho-hadoop-shims.version}-dist.zip
        - pentaho-hadoop-shims-ee-cdpdc71-kar-${pentaho-hadoop-shims.version}-dist.zip
        - pentaho-hadoop-shims-ee-hdi40-kar-${pentaho-hadoop-shims.version}-dist.zip
    container-images:
        - pdi-carte-ee-aws-${platform.version}.tar.gz
        - pdi-carte-ee-bigdata-aws-${platform.version}.tar.gz
        - pdi-cli-ee-aws-${platform.version}.tar.gz
        - pdi-cli-ee-bigdata-aws-${platform.version}.tar.gz
        - pdi-server-ee-aws-${platform.version}.tar.gz
        - platform-server-ee-aws-${platform.version}.tar.gz
        - pdi-carte-ee-azure-${platform.version}.tar.gz
        - pdi-carte-ee-bigdata-azure-${platform.version}.tar.gz
        - pdi-cli-ee-azure-${platform.version}.tar.gz
        - pdi-cli-ee-bigdata-azure-${platform.version}.tar.gz
        - pdi-server-ee-azure-${platform.version}.tar.gz
        - platform-server-ee-azure-${platform.version}.tar.gz
        - pdi-carte-ee-gcp-${platform.version}.tar.gz
        - pdi-carte-ee-bigdata-gcp-${platform.version}.tar.gz
        - pdi-cli-ee-gcp-${platform.version}.tar.gz
        - pdi-cli-ee-bigdata-gcp-${platform.version}.tar.gz
        - pdi-server-ee-gcp-${platform.version}.tar.gz
        - platform-server-ee-gcp-${platform.version}.tar.gz
    upgrade:
        - PentahoServer-UP-${platform.version}-Linux.zip
        - PentahoServer-UP-${platform.version}-Mac.zip
        - PentahoServer-UP-${platform.version}-Windows.zip
        - pentaho-upgrade-utility-${platform.version}-ba.zip
        - pentaho-upgrade-utility-${platform.version}-pdi.zip
        - pentaho-upgrade-utility-${platform.version}-pentaho.zip

#CE Stuff
ce:
    client-tools:
        - pad-ce-${platform.version}.zip
        - pdi-ce-${platform.version}.zip
        - pdi-ce-${platform.version}-hadoop-addon.zip
        - pentaho-big-data-plugin-${platform.version}.zip
        - pme-ce-${platform.version}.zip
        - pme-ce-${platform.version}-hadoop-addon.zip
        - prd-ce-${platform.version}.zip
        - prd-ce-${platform.version}-hadoop-addon.zip
        - psw-ce-${mondrian.version}.zip
    plugins:
        - kettle-sdk-plugin-assembly-${platform.version}.zip
    server:
        - pentaho-server-ce-${platform.version}.zip
        - pentaho-server-manual-ce-${platform.version}.zip
    other:
        - pre-classic-sdk-${platform.version}.zip

# Testable items, but not customer hand-off items
not-for-release:
    - pdi-ee-client-${platform.version}-osgi.zip
    - pme-ee-${platform.version}-osgi.zip
    - prd-ee-${platform.version}-osgi.zip
    - pdi-ce-${platform.version}-osgi.zip
    - pme-ce-${platform.version}-osgi.zip
    - prd-ce-${platform.version}-osgi.zip
    - pentaho-hadoop-shims-ee-cdh61-kar-${pentaho-hadoop-shims.version}.kar
    - pentaho-hadoop-shims-ee-emr521-kar-${pentaho-hadoop-shims.version}.kar
    - pentaho-hadoop-shims-ee-hdp30-kar-${pentaho-hadoop-shims.version}.kar
    - pentaho-hadoop-shims-ee-dataproc1421-kar-${pentaho-hadoop-shims.version}.kar
    - pentaho-hadoop-shims-ee-cdpdc71-kar-${pentaho-hadoop-shims.version}.kar
    - pentaho-hadoop-shims-ee-hdi40-kar-${pentaho-hadoop-shims.version}.kar
    