#
# This file is the manifest to determine which built items are copied to the
# hosted/Box file server locations. The versions that are specified within
# parenthesis below *must* match the versions from the version.properties file.
# They can also be overridden by passing values to the harvester script. ${see -versions}.
# It is best to keep the files and folders alphabetized because it makes it easier
# to compare the manifest to the filesystem. The exception to this is the ee/ce folder
# since most of the important artifacts are in the ee folder.
#

#EE Stuff
ee:
    client-tools:
        - pad-ee-${platform.version}.zip
        - pdi-ee-client-${platform.version}.zip
        - pentaho-analysis-ee-${platform.version}.zip
        - pentaho-big-data-ee-package-${platform.version}.zip
        - pme-ee-${platform.version}.zip
        - prd-ee-${platform.version}.zip
        - psw-ee-${mondrian.version}.zip
    installers:
        - pentaho-business-analytics-${platform.version}-x64.app.tar.gz
        - pentaho-business-analytics-${platform.version}-x64.bin
        - pentaho-business-analytics-${platform.version}-x64.exe
    other:
        - pentaho-operations-mart-${platform.version}.zip
        - pentaho-sdk-${platform.version}.zip
    patches:
        - SP${SP_RELEASE_VERSION}-${platform.version}-Linux.zip
        - SP${SP_RELEASE_VERSION}-${platform.version}-Mac.zip
        - SP${SP_RELEASE_VERSION}-${platform.version}-Windows.zip
    plugins:
        - paz-plugin-ee-${platform.version}.zip
        - pdd-plugin-ee-${platform.version}.zip
        - pdi-ee-plugin-${platform.version}.zip
        - pdi-hana-plugin-package-${platform.version}.zip
        - pentaho-geo-ee-${platform.version}.zip
        - pentaho-monitoring-plugin-mib-assembly-${platform.version}.zip
        - pir-plugin-ee-${platform.version}.zip
        - snowflake-plugins-${snowflake-plugin.version}.zip
    server:
        - pentaho-server-ee-${platform.version}.zip
        - pentaho-server-manual-ee-${platform.version}.zip
        - pentaho-workernodes-${platform.version}.zip
        - pentaho-workernodes-${platform.version}.tar.gz
    shims:
        - pentaho-big-data-ee-cdh512-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-cdh513-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-cdh514-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-cdh61-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-emr511-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-emr521-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-hdp25-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-hdp26-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-hdp30-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-mapr520-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-big-data-ee-mapr60-package-${pentaho-hadoop-shims.version}.zip
    upgrade:
        - pentaho-upgrade-utility-${platform.version}-ba.zip
        - pentaho-upgrade-utility-${platform.version}-pdi.zip
        - pentaho-upgrade-utility-${platform.version}-pentaho.zip

#CE Stuff
ce:
    client-tools:
        - pad-ce-${platform.version}.zip
        - pdi-ce-${platform.version}.zip
        - pentaho-big-data-plugin-${platform.version}.zip
        - pme-ce-${platform.version}.zip
        - prd-ce-${platform.version}.zip
        - psw-ce-${mondrian.version}.zip
    plugins:
        - kettle-sdk-plugin-assembly-${platform.version}.zip
    server:
        - pentaho-server-ce-${platform.version}.zip
        - pentaho-server-manual-ce-${platform.version}.zip
    shims:
        - pentaho-hadoop-shims-cdh512-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-cdh513-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-cdh514-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-cdh61-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-emr59-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-emr511-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-emr521-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-hdi35-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-hdp25-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-hdp26-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-hdp30-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-mapr520-package-${pentaho-hadoop-shims.version}.zip
        - pentaho-hadoop-shims-mapr60-package-${pentaho-hadoop-shims.version}.zip
    other:
        - pre-classic-sdk-${platform.version}.zip

# Testable items, but not customer hand-off items
not-for-release: